// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iibhnjdyteqblzrfiyah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpYmhuamR5dGVxYmx6cmZpeWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzc3MTgsImV4cCI6MjA2OTU1MzcxOH0.WV5QczLTAJ10L2KFjv8PhQqXTkzCwN0lE1IG0WV5yxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});